-- 1. Update HomeTeam in Silver.Matches
UPDATE Silver.Matches
SET HomeTeam = CASE HomeTeam
    WHEN 'Brighton' THEN 'Brighton & Hove Albion'
    WHEN 'Birmingham' THEN 'Birmingham City'
    WHEN 'Blackburn' THEN 'Blackburn Rovers'
    WHEN 'Bolton' THEN 'Bolton Wanderers'
    WHEN 'Bradford' THEN 'Bradford City'
    WHEN 'Burton' THEN 'Burton Albion'
    WHEN 'Cardiff' THEN 'Cardiff City'
    WHEN 'Charlton' THEN 'Charlton Athletic'
    WHEN 'Colchester' THEN 'Colchester United'
    WHEN 'Coventry' THEN 'Coventry City'
    WHEN 'Crewe' THEN 'Crewe Alexandra'
    WHEN 'Derby' THEN 'Derby County'
    WHEN 'Doncaster' THEN 'Doncaster Rovers'
    WHEN 'Huddersfield' THEN 'Huddersfield Town'
    WHEN 'Hull' THEN 'Hull City'
    WHEN 'Ipswich' THEN 'Ipswich Town'
    WHEN 'Leeds' THEN 'Leeds United'
    WHEN 'Leicester' THEN 'Leicester City'
    WHEN 'Luton' THEN 'Luton Town'
    WHEN 'Man City' THEN 'Manchester City'
    WHEN 'Man United' THEN 'Manchester United'
    WHEN 'Man Utd' THEN 'Manchester United'
    WHEN 'Milton Keynes Dons' THEN 'MK Dons'
    WHEN 'Newcastle' THEN 'Newcastle United'
    WHEN 'Norwich' THEN 'Norwich City'
    WHEN 'Nott''m Forest' THEN 'Nottingham Forest'
    WHEN 'Oxford' THEN 'Oxford United'
    WHEN 'Peterboro' THEN 'Peterborough United'
    WHEN 'Plymouth' THEN 'Plymouth Argyle'
    WHEN 'Preston' THEN 'Preston North End'
    WHEN 'QPR' THEN 'Queens Park Rangers'
    WHEN 'Rotherham' THEN 'Rotherham United'
    WHEN 'Scunthorpe' THEN 'Scunthorpe United'
    WHEN 'Sheffield Weds' THEN 'Sheffield Wednesday'
    WHEN 'Southend' THEN 'Southend United'
    WHEN 'Stoke' THEN 'Stoke City'
    WHEN 'Swansea' THEN 'Swansea City'
    WHEN 'Tottenham' THEN 'Tottenham Hotspur'
    WHEN 'Spurs' THEN 'Tottenham Hotspur'
    WHEN 'West Brom' THEN 'West Bromwich Albion'
    WHEN 'West Ham' THEN 'West Ham United'
    WHEN 'Wigan' THEN 'Wigan Athletic'
    WHEN 'Wolves' THEN 'Wolverhampton Wanderers'
    WHEN 'Wycombe' THEN 'Wycombe Wanderers'
    WHEN 'Yeovil' THEN 'Yeovil Town'
    ELSE HomeTeam
END;

-- 2. Update AwayTeam in Silver.Matches
UPDATE Silver.Matches
SET AwayTeam = CASE AwayTeam
    WHEN 'Brighton' THEN 'Brighton & Hove Albion'
    WHEN 'Birmingham' THEN 'Birmingham City'
    WHEN 'Blackburn' THEN 'Blackburn Rovers'
    WHEN 'Bolton' THEN 'Bolton Wanderers'
    WHEN 'Bradford' THEN 'Bradford City'
    WHEN 'Burton' THEN 'Burton Albion'
    WHEN 'Cardiff' THEN 'Cardiff City'
    WHEN 'Charlton' THEN 'Charlton Athletic'
    WHEN 'Colchester' THEN 'Colchester United'
    WHEN 'Coventry' THEN 'Coventry City'
    WHEN 'Crewe' THEN 'Crewe Alexandra'
    WHEN 'Derby' THEN 'Derby County'
    WHEN 'Doncaster' THEN 'Doncaster Rovers'
    WHEN 'Huddersfield' THEN 'Huddersfield Town'
    WHEN 'Hull' THEN 'Hull City'
    WHEN 'Ipswich' THEN 'Ipswich Town'
    WHEN 'Leeds' THEN 'Leeds United'
    WHEN 'Leicester' THEN 'Leicester City'
    WHEN 'Luton' THEN 'Luton Town'
    WHEN 'Man City' THEN 'Manchester City'
    WHEN 'Man United' THEN 'Manchester United'
    WHEN 'Man Utd' THEN 'Manchester United'
    WHEN 'Milton Keynes Dons' THEN 'MK Dons'
    WHEN 'Newcastle' THEN 'Newcastle United'
    WHEN 'Norwich' THEN 'Norwich City'
    WHEN 'Nott''m Forest' THEN 'Nottingham Forest'
    WHEN 'Oxford' THEN 'Oxford United'
    WHEN 'Peterboro' THEN 'Peterborough United'
    WHEN 'Plymouth' THEN 'Plymouth Argyle'
    WHEN 'Preston' THEN 'Preston North End'
    WHEN 'QPR' THEN 'Queens Park Rangers'
    WHEN 'Rotherham' THEN 'Rotherham United'
    WHEN 'Scunthorpe' THEN 'Scunthorpe United'
    WHEN 'Sheffield Weds' THEN 'Sheffield Wednesday'
    WHEN 'Southend' THEN 'Southend United'
    WHEN 'Stoke' THEN 'Stoke City'
    WHEN 'Swansea' THEN 'Swansea City'
    WHEN 'Tottenham' THEN 'Tottenham Hotspur'
    WHEN 'Spurs' THEN 'Tottenham Hotspur'
    WHEN 'West Brom' THEN 'West Bromwich Albion'
    WHEN 'West Ham' THEN 'West Ham United'
    WHEN 'Wigan' THEN 'Wigan Athletic'
    WHEN 'Wolves' THEN 'Wolverhampton Wanderers'
    WHEN 'Wycombe' THEN 'Wycombe Wanderers'
    WHEN 'Yeovil' THEN 'Yeovil Town'
    ELSE AwayTeam
END;

-- 3. Update HomeTeam in Silver.Matches_Historical
UPDATE Silver.Matches_Historical
SET HomeTeam = CASE HomeTeam
    WHEN 'Brighton' THEN 'Brighton & Hove Albion'
    WHEN 'Birmingham' THEN 'Birmingham City'
    WHEN 'Blackburn' THEN 'Blackburn Rovers'
    WHEN 'Bolton' THEN 'Bolton Wanderers'
    WHEN 'Bradford' THEN 'Bradford City'
    WHEN 'Burton' THEN 'Burton Albion'
    WHEN 'Cardiff' THEN 'Cardiff City'
    WHEN 'Charlton' THEN 'Charlton Athletic'
    WHEN 'Colchester' THEN 'Colchester United'
    WHEN 'Coventry' THEN 'Coventry City'
    WHEN 'Crewe' THEN 'Crewe Alexandra'
    WHEN 'Derby' THEN 'Derby County'
    WHEN 'Doncaster' THEN 'Doncaster Rovers'
    WHEN 'Huddersfield' THEN 'Huddersfield Town'
    WHEN 'Hull' THEN 'Hull City'
    WHEN 'Ipswich' THEN 'Ipswich Town'
    WHEN 'Leeds' THEN 'Leeds United'
    WHEN 'Leicester' THEN 'Leicester City'
    WHEN 'Luton' THEN 'Luton Town'
    WHEN 'Man City' THEN 'Manchester City'
    WHEN 'Man United' THEN 'Manchester United'
    WHEN 'Man Utd' THEN 'Manchester United'
    WHEN 'Milton Keynes Dons' THEN 'MK Dons'
    WHEN 'Newcastle' THEN 'Newcastle United'
    WHEN 'Norwich' THEN 'Norwich City'
    WHEN 'Nott''m Forest' THEN 'Nottingham Forest'
    WHEN 'Oxford' THEN 'Oxford United'
    WHEN 'Peterboro' THEN 'Peterborough United'
    WHEN 'Plymouth' THEN 'Plymouth Argyle'
    WHEN 'Preston' THEN 'Preston North End'
    WHEN 'QPR' THEN 'Queens Park Rangers'
    WHEN 'Rotherham' THEN 'Rotherham United'
    WHEN 'Scunthorpe' THEN 'Scunthorpe United'
    WHEN 'Sheffield Weds' THEN 'Sheffield Wednesday'
    WHEN 'Southend' THEN 'Southend United'
    WHEN 'Stoke' THEN 'Stoke City'
    WHEN 'Swansea' THEN 'Swansea City'
    WHEN 'Tottenham' THEN 'Tottenham Hotspur'
    WHEN 'Spurs' THEN 'Tottenham Hotspur'
    WHEN 'West Brom' THEN 'West Bromwich Albion'
    WHEN 'West Ham' THEN 'West Ham United'
    WHEN 'Wigan' THEN 'Wigan Athletic'
    WHEN 'Wolves' THEN 'Wolverhampton Wanderers'
    WHEN 'Wycombe' THEN 'Wycombe Wanderers'
    WHEN 'Yeovil' THEN 'Yeovil Town'
    ELSE HomeTeam
END;

-- 4. Update AwayTeam in Silver.Matches_Historical
UPDATE Silver.Matches_Historical
SET AwayTeam = CASE AwayTeam
    WHEN 'Brighton' THEN 'Brighton & Hove Albion'
    WHEN 'Birmingham' THEN 'Birmingham City'
    WHEN 'Blackburn' THEN 'Blackburn Rovers'
    WHEN 'Bolton' THEN 'Bolton Wanderers'
    WHEN 'Bradford' THEN 'Bradford City'
    WHEN 'Burton' THEN 'Burton Albion'
    WHEN 'Cardiff' THEN 'Cardiff City'
    WHEN 'Charlton' THEN 'Charlton Athletic'
    WHEN 'Colchester' THEN 'Colchester United'
    WHEN 'Coventry' THEN 'Coventry City'
    WHEN 'Crewe' THEN 'Crewe Alexandra'
    WHEN 'Derby' THEN 'Derby County'
    WHEN 'Doncaster' THEN 'Doncaster Rovers'
    WHEN 'Huddersfield' THEN 'Huddersfield Town'
    WHEN 'Hull' THEN 'Hull City'
    WHEN 'Ipswich' THEN 'Ipswich Town'
    WHEN 'Leeds' THEN 'Leeds United'
    WHEN 'Leicester' THEN 'Leicester City'
    WHEN 'Luton' THEN 'Luton Town'
    WHEN 'Man City' THEN 'Manchester City'
    WHEN 'Man United' THEN 'Manchester United'
    WHEN 'Man Utd' THEN 'Manchester United'
    WHEN 'Milton Keynes Dons' THEN 'MK Dons'
    WHEN 'Newcastle' THEN 'Newcastle United'
    WHEN 'Norwich' THEN 'Norwich City'
    WHEN 'Nott''m Forest' THEN 'Nottingham Forest'
    WHEN 'Oxford' THEN 'Oxford United'
    WHEN 'Peterboro' THEN 'Peterborough United'
    WHEN 'Plymouth' THEN 'Plymouth Argyle'
    WHEN 'Preston' THEN 'Preston North End'
    WHEN 'QPR' THEN 'Queens Park Rangers'
    WHEN 'Rotherham' THEN 'Rotherham United'
    WHEN 'Scunthorpe' THEN 'Scunthorpe United'
    WHEN 'Sheffield Weds' THEN 'Sheffield Wednesday'
    WHEN 'Southend' THEN 'Southend United'
    WHEN 'Stoke' THEN 'Stoke City'
    WHEN 'Swansea' THEN 'Swansea City'
    WHEN 'Tottenham' THEN 'Tottenham Hotspur'
    WHEN 'Spurs' THEN 'Tottenham Hotspur'
    WHEN 'West Brom' THEN 'West Bromwich Albion'
    WHEN 'West Ham' THEN 'West Ham United'
    WHEN 'Wigan' THEN 'Wigan Athletic'
    WHEN 'Wolves' THEN 'Wolverhampton Wanderers'
    WHEN 'Wycombe' THEN 'Wycombe Wanderers'
    WHEN 'Yeovil' THEN 'Yeovil Town'
    ELSE AwayTeam
END;




-- Check remaining non-standard names in Matches
SELECT DISTINCT HomeTeam FROM Silver.Matches
UNION
SELECT DISTINCT AwayTeam FROM Silver.Matches
ORDER BY HomeTeam;

-- Check remaining non-standard names in Matches_Historical
SELECT DISTINCT HomeTeam FROM Silver.Matches_Historical
UNION
SELECT DISTINCT AwayTeam FROM Silver.Matches_Historical
ORDER BY HomeTeam;